const GET_HOME_INFO = "GET_HOME_INFO"
const GET_NAV_INFO = "GET_NAV_INFO"
const CHANGE_ACTIVE_INDEX = "CHANGE_ACTIVE_INDEX"
const CHANGE_SCROLL_FLAG = "CHANGE_SCROLL_FLAG"
export {GET_HOME_INFO,GET_NAV_INFO,CHANGE_ACTIVE_INDEX,CHANGE_SCROLL_FLAG}